### ISSUE TITLE
compile 'com.afollestad:material-dialogs:0.7.6.0'

### ISSUE THREAD

**Issue by chenleicpp** [chenyangcun/MaterialDesignExample#1]
这个库导致编译失败，不太明白什么原因
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.afollestad:material-dialogs:0.7.6.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.pom
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.jar
         file:/E:/android/adt-bundle-windows-x86_64-20130917/sdk/extras/android/m2repository/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.pom
         file:/E:/android/adt-bundle-windows-x86_64-20130917/sdk/extras/android/m2repository/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.jar
         file:/E:/android/adt-bundle-windows-x86_64-20130917/sdk/extras/google/m2repository/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.pom
         file:/E:/android/adt-bundle-windows-x86_64-20130917/sdk/extras/google/m2repository/com/afollestad/material-dialogs/0.7.6.0/material-dialogs-0.7.6.0.jar
     Required by:
         MaterialDesignExample-master:app:unspecified

**Comment by basefas** [comment]
The same question.

**Comment by chenyangcun** [comment]
已修复 https://github.com/chenyangcun/MaterialDesignExample/commit/89c683ef408781c711bc451a23ecf40571768d8e
